sudo: required 

services:
  - docker

before_install:
  - docker build -t dkwitt/devops -f mydockerfrontend/Dockerfile.dev mydockerfrontend/.

script: 
  - docker run -e CI=true dkwitt/DevOps yarn test 
